nextflow.enable.dsl = 2


/*
===============================================================================
Genomics England CloudOS GWAS / REGENIE

Task 2: REGENIE Step 2 Genome-wide Association Testing

Phenotype
---------
Cutaneous melanoma (CM)

Binary trait:
    0 = control
    1 = case


Dataset
-------
Genomics England (GEL) AggV3 WGS


Purpose
-------
Perform chromosome-specific genome-wide association testing using REGENIE
Step 2 with LOCO predictions generated from REGENIE Step 1.


Input genotype
--------------
Chromosome-specific AggV3 PGEN files:

    dragen.pgen
    dragen.pvar
    dragen.psam


Variant QC
----------
Only variants passing site-level QC are tested:

    FILTER = PASS or LowMLSQ

provided through chromosome-specific variant-ID lists:

    chrN.PASS_or_LowMLSQ.variant_ids.txt


Association model
-----------------
REGENIE Step 2:

    - binary logistic regression
    - additive model
    - LOCO prediction adjustment
    - approximate Firth correction


Covariates
-----------
Included:

    - genetic_sex
    - study_source
    - year_of_birth
    - PC1-PC20


Categorical covariates:

    - genetic_sex
    - study_source


Parallelization
---------------
chr1-chr22 independently


Software
--------
REGENIE v4.1.2


Container
---------
Defined in nextflow.config


Author:
Shelley

===============================================================================
*/


/*
-------------------------------------------------------------------------------
Pipeline parameters
-------------------------------------------------------------------------------
*/


params.pgen_root = null

params.variant_list_dir = null


params.pheno_file = null

params.covar_file = null


/*
REGENIE Step 1 LOCO prediction file

Example:

GEL_CM_REGENIE_step1_1.loco

The original pred.list generated by Nextflow is NOT reused because
it contains temporary /tmp/nxf.* paths.
*/

params.step1_loco = null


params.outdir = "regenie.step2.GWAS"


params.bsize = 400



/*
-------------------------------------------------------------------------------
Process: REGENIE Step 2
-------------------------------------------------------------------------------
*/


process REGENIE_STEP2 {


    tag "chr${chr}"


    /*
    Container is defined in nextflow.config

    Example:

    ghcr.io/shiyuzhang0522/regenie:4.1.2

    */


    cpus 16

    memory "40 GB"

    time "7d"



    publishDir "${params.outdir}/chr${chr}",
        mode: "copy"



    input:


    tuple val(chr),
          path(pgen, name: "dragen.pgen"),
          path(pvar, name: "dragen.pvar"),
          path(psam, name: "dragen.psam"),
          path(variant_list, name: "variant_ids.txt")


    path phenotype,
         name: "GEL_CM_REGENIE.phenotype.tsv"


    path covariates,
         name: "GEL_CM_REGENIE.covariates.tsv"


    path loco,
         name: "GEL_CM_REGENIE_step1_1.loco"



    output:


    path "chr${chr}.GEL_CM_REGENIE_step2.regenie.gz"

    path "chr${chr}.GEL_CM_REGENIE_step2.log"

    path "chr${chr}.GEL_CM_REGENIE_step2.*"



    script:


    """

    set -euo pipefail


    echo "============================================================"
    echo "REGENIE Step 2 GWAS"
    echo "Chromosome: chr${chr}"
    echo "Start time: \$(date)"
    echo "Hostname:   \$(hostname)"
    echo "Threads:    ${task.cpus}"
    echo "============================================================"



    echo
    echo "Input files:"
    echo "PGEN:"
    ls -lh dragen.pgen

    echo
    echo "PVAR:"
    ls -lh dragen.pvar

    echo
    echo "PSAM:"
    ls -lh dragen.psam



    echo
    echo "Variant list:"
    echo "Variants supplied:"
    wc -l variant_ids.txt



    echo
    echo "Step 1 LOCO prediction:"
    ls -lh GEL_CM_REGENIE_step1_1.loco



    # -------------------------------------------------------------------------
    # Input validation
    # -------------------------------------------------------------------------


    for file in \
        dragen.pgen \
        dragen.pvar \
        dragen.psam \
        variant_ids.txt \
        GEL_CM_REGENIE.phenotype.tsv \
        GEL_CM_REGENIE.covariates.tsv \
        GEL_CM_REGENIE_step1_1.loco

    do

        if [[ ! -s "${file}" ]]; then

            echo "ERROR: missing or empty input file: ${file}" >&2
            exit 1

        fi

    done



    # -------------------------------------------------------------------------
    # Generate local REGENIE prediction list
    #
    # Avoid /tmp/nxf.* paths generated by Step 1 Nextflow task
    # -------------------------------------------------------------------------


    cat > GEL_CM_REGENIE_step1_pred.list << EOF
CM GEL_CM_REGENIE_step1_1.loco
EOF



    echo
    echo "Generated prediction list:"
    cat GEL_CM_REGENIE_step1_pred.list



    # -------------------------------------------------------------------------
    # REGENIE Step 2
    # -------------------------------------------------------------------------


    regenie \
        --step 2 \
        --pgen dragen \
        --extract variant_ids.txt \
        --phenoFile GEL_CM_REGENIE.phenotype.tsv \
        --phenoCol CM \
        --covarFile GEL_CM_REGENIE.covariates.tsv \
        --catCovarList genetic_sex,study_source \
        --maxCatLevels 30 \
        --pred GEL_CM_REGENIE_step1_pred.list \
        --bt \
        --minMAC 20 \
        --firth \
        --approx \
        --firth-se \
        --pThresh 0.01 \
        --bsize ${params.bsize} \
        --threads ${task.cpus} \
        --gz \
        --out chr${chr}.GEL_CM_REGENIE_step2



    # -------------------------------------------------------------------------
    # Output validation
    # -------------------------------------------------------------------------


    if [[ ! -s chr${chr}.GEL_CM_REGENIE_step2.regenie.gz ]]; then

        echo "ERROR: REGENIE output missing for chr${chr}" >&2
        exit 1

    fi



    echo
    echo "============================================================"
    echo "chr${chr} REGENIE Step 2 completed"
    echo "End time: \$(date)"
    echo "Output:"
    echo "chr${chr}.GEL_CM_REGENIE_step2.regenie.gz"
    echo "============================================================"


    """

}

/*
-------------------------------------------------------------------------------
Workflow
-------------------------------------------------------------------------------
*/


workflow {


    /*
    ---------------------------------------------------------------------------
    Validate required parameters
    ---------------------------------------------------------------------------
    */


    if (!params.pgen_root) {

        error """
        Missing required parameter: --pgen_root

        Expected structure:

        <pgen_root>/chrom-1/postproc-pgen/dragen.pgen
        <pgen_root>/chrom-1/postproc-pgen/dragen.pvar
        <pgen_root>/chrom-1/postproc-pgen/dragen.psam

        ...
        
        <pgen_root>/chrom-22/postproc-pgen/dragen.*
        """.stripIndent()

    }



    if (!params.variant_list_dir) {

        error """
        Missing required parameter: --variant_list_dir

        Expected structure:

        <variant_list_dir>/chr1.PASS_or_LowMLSQ.variant_ids.txt

        ...

        <variant_list_dir>/chr22.PASS_or_LowMLSQ.variant_ids.txt

        """.stripIndent()

    }



    if (!params.pheno_file) {

        error """
        Missing required parameter: --pheno_file

        Expected:

        GEL_CM_REGENIE.phenotype.tsv

        """.stripIndent()

    }



    if (!params.covar_file) {

        error """
        Missing required parameter: --covar_file

        Expected:

        GEL_CM_REGENIE.covariates.tsv

        """.stripIndent()

    }



    if (!params.step1_loco) {

        error """
        Missing required parameter: --step1_loco

        Expected:

        GEL_CM_REGENIE_step1_1.loco

        """.stripIndent()

    }




    /*
    ---------------------------------------------------------------------------
    Construct chromosome-specific genotype channels
    ---------------------------------------------------------------------------

    Each emitted tuple:

        [
          chromosome,
          pgen,
          pvar,
          psam,
          QC variant list
        ]

    One tuple = one REGENIE Step 2 task.

    Therefore:

        chr1  --> one AWS Batch task
        chr2  --> one AWS Batch task
        ...
        chr22 --> one AWS Batch task

    ---------------------------------------------------------------------------
    */


    genotype_ch = Channel
        .fromList((1..22).toList())
        .map { chr ->


            def pgen = file(
                "${params.pgen_root}/chrom-${chr}/postproc-pgen/dragen.pgen",
                checkIfExists: true
            )


            def pvar = file(
                "${params.pgen_root}/chrom-${chr}/postproc-pgen/dragen.pvar",
                checkIfExists: true
            )


            def psam = file(
                "${params.pgen_root}/chrom-${chr}/postproc-pgen/dragen.psam",
                checkIfExists: true
            )


            def variant_list = file(
                "${params.variant_list_dir}/chr${chr}.PASS_or_LowMLSQ.variant_ids.txt",
                checkIfExists: true
            )



            tuple(
                chr,
                pgen,
                pvar,
                psam,
                variant_list
            )

        }




    /*
    ---------------------------------------------------------------------------
    Shared input files
    ---------------------------------------------------------------------------

    These files are identical for all chromosomes.

    Channel.value() broadcasts the same file to all REGENIE tasks.

    ---------------------------------------------------------------------------
    */


    phenotype_ch =
        Channel.value(
            file(
                params.pheno_file,
                checkIfExists: true
            )
        )



    covariates_ch =
        Channel.value(
            file(
                params.covar_file,
                checkIfExists: true
            )
        )



    loco_ch =
        Channel.value(
            file(
                params.step1_loco,
                checkIfExists: true
            )
        )



    /*
    ---------------------------------------------------------------------------
    Launch REGENIE Step 2
    ---------------------------------------------------------------------------
    */


    REGENIE_STEP2(
        genotype_ch,
        phenotype_ch,
        covariates_ch,
        loco_ch
    )

}