nextflow.enable.dsl = 2

/*
===============================================================================
Genomics England CloudOS GWAS / REGENIE

Step 2: LD pruning

Purpose
-------
Perform chromosome-specific LD pruning on the high-quality common SNP genotype
datasets generated by 01_shared_QC.

The LD-pruning stage is intentionally separated from the upstream shared QC so
that different pruning parameters can be tested without regenerating the large
HQ-common PGEN datasets.

Default pruning parameters
--------------------------
Window: 500 kb
r^2:    0.2

Input structure
---------------
<hq_pgen_root>/
├── chr1/
│   ├── chr1.HQ_common.pgen
│   ├── chr1.HQ_common.pvar
│   └── chr1.HQ_common.psam
├── chr2/
│   └── ...
...
└── chr22/

Outputs
-------
Per chromosome:
  chrN.LD_pruned.prune.in
  chrN.LD_pruned.prune.out
  chrN.LD_pruned.summary.tsv
  chrN.LD_pruned.log

Genome-wide:
  REGENIE_step1.LD_pruned.variant_ids.txt
  LD_pruning.all_chr.summary.tsv
  LD_pruning.genomewide.summary.tsv

Author: Shelley
===============================================================================
*/


/*
-------------------------------------------------------------------------------
Runtime parameters
-------------------------------------------------------------------------------
*/

params.hq_pgen_root = null

params.window = '500kb'
params.r2     = 0.2

params.outdir = 'results'


/*
-------------------------------------------------------------------------------
Process 1: chromosome-specific LD pruning
-------------------------------------------------------------------------------
*/

process LD_PRUNE {

    tag "chr${chr}"

    container params.plink2_image

    publishDir "${params.outdir}/chr${chr}", mode: 'copy'


    input:

    tuple val(chr),
          path(pgen, name: 'HQ_common.pgen'),
          path(pvar, name: 'HQ_common.pvar'),
          path(psam, name: 'HQ_common.psam')


    output:

    tuple val(chr),
          path("chr${chr}.LD_pruned.prune.in"),
          path("chr${chr}.LD_pruned.prune.out"),
          path("chr${chr}.LD_pruned.summary.tsv"),
          emit: prune_results

    path "chr${chr}.LD_pruned.log",
         emit: prune_logs


    script:

    """
    set -euo pipefail

    echo "============================================================"
    echo "GEL REGENIE LD pruning"
    echo "Chromosome: chr${chr}"
    echo "============================================================"
    echo
    echo "Parameters:"
    echo "  Window : ${params.window}"
    echo "  r2     : ${params.r2}"
    echo "  Threads: ${task.cpus}"
    echo


    # -------------------------------------------------------------------------
    # Input sanity checks
    # -------------------------------------------------------------------------

    [[ -s HQ_common.pgen ]] || {
        echo "ERROR: missing or empty PGEN" >&2
        exit 1
    }

    [[ -s HQ_common.pvar ]] || {
        echo "ERROR: missing or empty PVAR" >&2
        exit 1
    }

    [[ -s HQ_common.psam ]] || {
        echo "ERROR: missing or empty PSAM" >&2
        exit 1
    }


    input_variants=\$(
        grep -vc '^#' HQ_common.pvar
    )

    input_samples=\$(
        awk '
            !/^#/ { n++ }
            END { print n+0 }
        ' HQ_common.psam
    )


    if [[ "\${input_variants}" -eq 0 ]]; then
        echo "ERROR: no variants detected in input PVAR" >&2
        exit 1
    fi


    if [[ "\${input_samples}" -eq 0 ]]; then
        echo "ERROR: no samples detected in input PSAM" >&2
        exit 1
    fi


    echo "Input variants: \${input_variants}"
    echo "Input samples : \${input_samples}"
    echo


    # -------------------------------------------------------------------------
    # LD pruning
    # -------------------------------------------------------------------------

    plink2 \\
        --pfile HQ_common \\
        --indep-pairwise ${params.window} ${params.r2} \\
        --threads ${task.cpus} \\
        --out chr${chr}.LD_pruned


    # -------------------------------------------------------------------------
    # Post-pruning sanity checks
    # -------------------------------------------------------------------------

    for file in \\
        chr${chr}.LD_pruned.prune.in \\
        chr${chr}.LD_pruned.prune.out \\
        chr${chr}.LD_pruned.log
    do
        [[ -s "\${file}" ]] || {
            echo "ERROR: expected output missing or empty: \${file}" >&2
            exit 1
        }
    done


    retained_variants=\$(
        wc -l < chr${chr}.LD_pruned.prune.in
    )

    removed_variants=\$(
        wc -l < chr${chr}.LD_pruned.prune.out
    )

    accounted_variants=\$(
        awk \
            -v retained="\${retained_variants}" \
            -v removed="\${removed_variants}" \
            'BEGIN { print retained + removed }'
    )


    if [[ "\${accounted_variants}" -ne "\${input_variants}" ]]; then
        echo "ERROR: retained + removed variants do not equal input variants" >&2
        echo "Input     : \${input_variants}" >&2
        echo "Retained  : \${retained_variants}" >&2
        echo "Removed   : \${removed_variants}" >&2
        echo "Accounted : \${accounted_variants}" >&2
        exit 1
    fi


    if [[ "\${retained_variants}" -eq 0 ]]; then
        echo "ERROR: no variants retained after LD pruning" >&2
        exit 1
    fi


    duplicate_retained_ids=\$(
        sort chr${chr}.LD_pruned.prune.in |
        uniq -d |
        wc -l
    )


    if [[ "\${duplicate_retained_ids}" -ne 0 ]]; then
        echo "ERROR: duplicate IDs detected in prune.in" >&2
        exit 1
    fi


    proportion_retained=\$(
        awk \
            -v retained="\${retained_variants}" \
            -v total="\${input_variants}" \
            'BEGIN {
                printf "%.6f", retained / total
            }'
    )


    # -------------------------------------------------------------------------
    # Per-chromosome summary
    # -------------------------------------------------------------------------

    printf "chromosome\\tinput_variants\\tretained_variants\\tremoved_variants\\tproportion_retained\\tinput_samples\\twindow\\tr2\\n" \
        > chr${chr}.LD_pruned.summary.tsv

    printf "chr${chr}\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n" \
        "\${input_variants}" \
        "\${retained_variants}" \
        "\${removed_variants}" \
        "\${proportion_retained}" \
        "\${input_samples}" \
        "${params.window}" \
        "${params.r2}" \
        >> chr${chr}.LD_pruned.summary.tsv


    echo
    echo "============================================================"
    echo "chr${chr} LD pruning completed"
    echo "============================================================"
    echo "Input variants      : \${input_variants}"
    echo "Retained variants   : \${retained_variants}"
    echo "Removed variants    : \${removed_variants}"
    echo "Proportion retained : \${proportion_retained}"
    echo "Samples             : \${input_samples}"
    echo "============================================================"
    """
}


/*
-------------------------------------------------------------------------------
Process 2: combine chromosome-specific results
-------------------------------------------------------------------------------
*/

process COMBINE_PRUNED_LISTS {

    tag "genome-wide"

    publishDir "${params.outdir}", mode: 'copy'


    input:

    path prune_files
    path summary_files


    output:

    path "REGENIE_step1.LD_pruned.variant_ids.txt"
    path "LD_pruning.all_chr.summary.tsv"
    path "LD_pruning.genomewide.summary.tsv"


    script:

    """
    set -euo pipefail


    # -------------------------------------------------------------------------
    # Check that all 22 chromosome outputs are present
    # -------------------------------------------------------------------------

    n_prune_files=\$(
        find . -maxdepth 1 \
            -name 'chr*.LD_pruned.prune.in' \
            -type f |
        wc -l
    )

    n_summary_files=\$(
        find . -maxdepth 1 \
            -name 'chr*.LD_pruned.summary.tsv' \
            -type f |
        wc -l
    )


    if [[ "\${n_prune_files}" -ne 22 ]]; then
        echo "ERROR: expected 22 prune.in files, found \${n_prune_files}" >&2
        exit 1
    fi


    if [[ "\${n_summary_files}" -ne 22 ]]; then
        echo "ERROR: expected 22 chromosome summary files, found \${n_summary_files}" >&2
        exit 1
    fi


    # -------------------------------------------------------------------------
    # Combine retained variant IDs in chromosome order
    # -------------------------------------------------------------------------

    : > REGENIE_step1.LD_pruned.variant_ids.txt

    for chr in {1..22}; do

        file="chr\${chr}.LD_pruned.prune.in"

        [[ -s "\${file}" ]] || {
            echo "ERROR: missing prune.in for chr\${chr}" >&2
            exit 1
        }

        cat "\${file}" \
            >> REGENIE_step1.LD_pruned.variant_ids.txt
    done


    # -------------------------------------------------------------------------
    # Combine chromosome summaries in chromosome order
    # -------------------------------------------------------------------------

    head -n 1 chr1.LD_pruned.summary.tsv \
        > LD_pruning.all_chr.summary.tsv


    for chr in {1..22}; do

        file="chr\${chr}.LD_pruned.summary.tsv"

        [[ -s "\${file}" ]] || {
            echo "ERROR: missing summary for chr\${chr}" >&2
            exit 1
        }

        tail -n 1 "\${file}" \
            >> LD_pruning.all_chr.summary.tsv
    done


    # -------------------------------------------------------------------------
    # Genome-wide summary
    # -------------------------------------------------------------------------

    awk -F'\\t' '
        NR == 1 {
            next
        }

        {
            n_chr++
            input_variants    += \$2
            retained_variants += \$3
            removed_variants  += \$4
        }

        END {

            print "metric\\tvalue"

            print "chromosomes\\t" n_chr

            print "input_variants\\t" \
                  input_variants

            print "retained_variants\\t" \
                  retained_variants

            print "removed_variants\\t" \
                  removed_variants

            if (input_variants > 0) {

                printf "proportion_retained\\t%.6f\\n", \
                       retained_variants / input_variants

            } else {

                print "proportion_retained\\tNA"
            }
        }
    ' LD_pruning.all_chr.summary.tsv \
        > LD_pruning.genomewide.summary.tsv


    printf "window\\t%s\\n" "${params.window}" \
        >> LD_pruning.genomewide.summary.tsv

    printf "r2\\t%s\\n" "${params.r2}" \
        >> LD_pruning.genomewide.summary.tsv


    # -------------------------------------------------------------------------
    # Final genome-wide sanity checks
    # -------------------------------------------------------------------------

    combined_variants=\$(
        wc -l < REGENIE_step1.LD_pruned.variant_ids.txt
    )

    summary_variants=\$(
        awk -F'\\t' '
            \$1 == "retained_variants" {
                print \$2
            }
        ' LD_pruning.genomewide.summary.tsv
    )


    if [[ "\${combined_variants}" -ne "\${summary_variants}" ]]; then
        echo "ERROR: genome-wide SNP list count differs from summary" >&2
        echo "Variant list: \${combined_variants}" >&2
        echo "Summary     : \${summary_variants}" >&2
        exit 1
    fi


    duplicate_ids=\$(
        sort REGENIE_step1.LD_pruned.variant_ids.txt |
        uniq -d |
        wc -l
    )


    if [[ "\${duplicate_ids}" -ne 0 ]]; then
        echo "ERROR: duplicate IDs detected in genome-wide SNP list" >&2
        exit 1
    fi


    chromosomes=\$(
        awk -F'\\t' '
            NR > 1 { n++ }
            END { print n+0 }
        ' LD_pruning.all_chr.summary.tsv
    )


    if [[ "\${chromosomes}" -ne 22 ]]; then
        echo "ERROR: genome-wide summary does not contain 22 chromosomes" >&2
        exit 1
    fi


    echo
    echo "============================================================"
    echo "Genome-wide LD pruning completed"
    echo "============================================================"
    echo "Window            : ${params.window}"
    echo "r2                : ${params.r2}"
    echo "Retained variants : \${combined_variants}"
    echo "Chromosomes       : \${chromosomes}"
    echo "============================================================"
    """
}


/*
-------------------------------------------------------------------------------
Workflow
-------------------------------------------------------------------------------
*/

workflow {

    /*
    Required runtime input.
    */

    if (!params.hq_pgen_root) {

        error """
        Missing required parameter: --hq_pgen_root

        Expected structure:

          <hq_pgen_root>/
          ├── chr1/
          │   ├── chr1.HQ_common.pgen
          │   ├── chr1.HQ_common.pvar
          │   └── chr1.HQ_common.psam
          ├── chr2/
          │   └── ...
          ...
          └── chr22/
        """.stripIndent()
    }


    /*
    Validate pruning parameters.
    */

    if (!(params.window ==~ /^[1-9][0-9]*(kb)?$/)) {

        error """
        Invalid --window value: ${params.window}

        Examples:
          500kb
          200kb
          1000
        """.stripIndent()
    }


    if (!(params.r2 instanceof Number) ||
        params.r2 <= 0 ||
        params.r2 >= 1) {

        error """
        Invalid --r2 value: ${params.r2}

        r2 must be > 0 and < 1.
        """.stripIndent()
    }


    /*
    Construct chromosome-specific genotype tuples.
    */

    genotype_ch = Channel
        .fromList((1..22).toList())
        .map { chr ->

            def pgen = file(
                "${params.hq_pgen_root}/chr${chr}/chr${chr}.HQ_common.pgen",
                checkIfExists: true
            )

            def pvar = file(
                "${params.hq_pgen_root}/chr${chr}/chr${chr}.HQ_common.pvar",
                checkIfExists: true
            )

            def psam = file(
                "${params.hq_pgen_root}/chr${chr}/chr${chr}.HQ_common.psam",
                checkIfExists: true
            )

            tuple(
                chr,
                pgen,
                pvar,
                psam
            )
        }


    /*
    Run chr1-22 LD pruning independently.
    */

    LD_PRUNE(
        genotype_ch
    )


    /*
    Collect pruning lists and summaries after all chromosome jobs complete.
    */

    prune_files_ch = LD_PRUNE.out.prune_results
        .map { chr, prune_in, prune_out, summary ->
            prune_in
        }
        .collect()


    summary_files_ch = LD_PRUNE.out.prune_results
        .map { chr, prune_in, prune_out, summary ->
            summary
        }
        .collect()


    /*
    Generate genome-wide retained-SNP list and summary.
    */

    COMBINE_PRUNED_LISTS(
        prune_files_ch,
        summary_files_ch
    )
}